"""baseline stable tables

Revision ID: 149862fa154b
Revises: 
Create Date: 2026-09-22 11:17:50.342178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149862fa154b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oss_upload_cache',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('oss_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oss_upload_cache_file_sha256'), 'oss_upload_cache', ['file_sha256'], unique=True)
    op.create_table('recognition_task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_no', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('total_photos', sa.Integer(), nullable=False),
    sa.Column('processed_photos', sa.Integer(), nullable=False),
    sa.Column('succeeded_photos', sa.Integer(), nullable=False),
    sa.Column('blocked_photos', sa.Integer(), nullable=False),
    sa.Column('failed_photos', sa.Integer(), nullable=False),
    sa.Column('task_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recognition_task_status'), 'recognition_task', ['status'], unique=False)
    op.create_index(op.f('ix_recognition_task_task_no'), 'recognition_task', ['task_no'], unique=True)
    op.create_table('import_job',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('created_photos', sa.Integer(), nullable=False),
    sa.Column('skipped_photos', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['recognition_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_job_status'), 'import_job', ['status'], unique=False)
    op.create_index(op.f('ix_import_job_task_id'), 'import_job', ['task_id'], unique=False)
    op.create_table('recognition_photo',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('source_row_id', sa.String(length=64), nullable=True),
    sa.Column('source_photo_type', sa.String(length=64), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('image_name', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('oss_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='photostatus'), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'PROCESSED', 'BLOCKED', 'FAILED', 'CANCELLED', name='photooutcome'), nullable=False),
    sa.Column('current_stage', sa.Enum('UPLOAD', 'QUALITY_CHECK', 'PRICE_RECOGNITION', 'POSTPROCESS', 'DONE', name='processstage'), nullable=False),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_type', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['recognition_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'dedupe_key', name='uq_photo_task_dedupe')
    )
    op.create_index('ix_photo_queue', 'recognition_photo', ['status', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_recognition_photo_file_sha256'), 'recognition_photo', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_recognition_photo_source_row_id'), 'recognition_photo', ['source_row_id'], unique=False)
    op.create_index(op.f('ix_recognition_photo_status'), 'recognition_photo', ['status'], unique=False)
    op.create_index(op.f('ix_recognition_photo_task_id'), 'recognition_photo', ['task_id'], unique=False)
    op.create_index(op.f('ix_recognition_photo_url_hash'), 'recognition_photo', ['url_hash'], unique=False)
    op.create_table('recognition_run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=False),
    sa.Column('run_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'PROCESSED', 'BLOCKED', 'FAILED', 'CANCELLED', name='photooutcome'), nullable=False),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['recognition_photo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'run_no', name='uq_photo_run_no')
    )
    op.create_index(op.f('ix_recognition_run_photo_id'), 'recognition_run', ['photo_id'], unique=False)
    op.create_table('ai_call_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('ability', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('business_status', sa.String(length=32), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['recognition_photo.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recognition_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_log_photo_id'), 'ai_call_log', ['photo_id'], unique=False)
    op.create_index(op.f('ix_ai_call_log_run_id'), 'ai_call_log', ['run_id'], unique=False)
    op.create_index('ix_ai_call_photo_ability', 'ai_call_log', ['photo_id', 'ability'], unique=False)
    op.create_table('price_result',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('total_raw_tags', sa.Integer(), nullable=False),
    sa.Column('total_tags', sa.Integer(), nullable=False),
    sa.Column('total_promotion_tags', sa.Integer(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('recognition_mode', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('postprocess_version', sa.String(length=64), nullable=True),
    sa.Column('model_cost_sec', sa.Float(), nullable=True),
    sa.Column('filter_events', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['recognition_photo.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recognition_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_result_photo_id'), 'price_result', ['photo_id'], unique=False)
    op.create_index(op.f('ix_price_result_run_id'), 'price_result', ['run_id'], unique=False)
    op.create_table('qc_result',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('should_continue', sa.Boolean(), nullable=True),
    sa.Column('qc_blur', sa.String(length=32), nullable=True),
    sa.Column('qc_over_exposure', sa.String(length=32), nullable=True),
    sa.Column('qc_low_light', sa.String(length=32), nullable=True),
    sa.Column('qc_file_corrupted', sa.String(length=32), nullable=True),
    sa.Column('invalid_reason', sa.Text(), nullable=True),
    sa.Column('invalid_reasons', sa.JSON(), nullable=False),
    sa.Column('scene_type', sa.String(length=64), nullable=True),
    sa.Column('scene_group', sa.String(length=32), nullable=True),
    sa.Column('has_price_tag', sa.Boolean(), nullable=False),
    sa.Column('is_quality_pass', sa.Boolean(), nullable=False),
    sa.Column('is_target_scene', sa.Boolean(), nullable=False),
    sa.Column('can_proceed_to_price', sa.Boolean(), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('model_cost_sec', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['recognition_photo.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recognition_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_result_photo_id'), 'qc_result', ['photo_id'], unique=False)
    op.create_index(op.f('ix_qc_result_run_id'), 'qc_result', ['run_id'], unique=False)
    op.create_table('price_tag_detail',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('price_result_id', sa.String(length=32), nullable=False),
    sa.Column('photo_id', sa.String(length=32), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('shelf_layer', sa.Integer(), nullable=True),
    sa.Column('bbox_xmin', sa.Float(), nullable=True),
    sa.Column('bbox_ymin', sa.Float(), nullable=True),
    sa.Column('bbox_xmax', sa.Float(), nullable=True),
    sa.Column('bbox_ymax', sa.Float(), nullable=True),
    sa.Column('coordinate_scale', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raw_price_text', sa.String(length=255), nullable=True),
    sa.Column('tag_type', sa.String(length=64), nullable=True),
    sa.Column('promotion_type', sa.String(length=64), nullable=True),
    sa.Column('bundle_quantity', sa.Integer(), nullable=True),
    sa.Column('bundle_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('second_item_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('price_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_reason', sa.String(length=255), nullable=True),
    sa.Column('is_promotion', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['recognition_photo.id'], ),
    sa.ForeignKeyConstraint(['price_result_id'], ['price_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_tag_detail_photo_id'), 'price_tag_detail', ['photo_id'], unique=False)
    op.create_index(op.f('ix_price_tag_detail_price_result_id'), 'price_tag_detail', ['price_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_tag_detail_price_result_id'), table_name='price_tag_detail')
    op.drop_index(op.f('ix_price_tag_detail_photo_id'), table_name='price_tag_detail')
    op.drop_table('price_tag_detail')
    op.drop_index(op.f('ix_qc_result_run_id'), table_name='qc_result')
    op.drop_index(op.f('ix_qc_result_photo_id'), table_name='qc_result')
    op.drop_table('qc_result')
    op.drop_index(op.f('ix_price_result_run_id'), table_name='price_result')
    op.drop_index(op.f('ix_price_result_photo_id'), table_name='price_result')
    op.drop_table('price_result')
    op.drop_index('ix_ai_call_photo_ability', table_name='ai_call_log')
    op.drop_index(op.f('ix_ai_call_log_run_id'), table_name='ai_call_log')
    op.drop_index(op.f('ix_ai_call_log_photo_id'), table_name='ai_call_log')
    op.drop_table('ai_call_log')
    op.drop_index(op.f('ix_recognition_run_photo_id'), table_name='recognition_run')
    op.drop_table('recognition_run')
    op.drop_index(op.f('ix_recognition_photo_url_hash'), table_name='recognition_photo')
    op.drop_index(op.f('ix_recognition_photo_task_id'), table_name='recognition_photo')
    op.drop_index(op.f('ix_recognition_photo_status'), table_name='recognition_photo')
    op.drop_index(op.f('ix_recognition_photo_source_row_id'), table_name='recognition_photo')
    op.drop_index(op.f('ix_recognition_photo_file_sha256'), table_name='recognition_photo')
    op.drop_index('ix_photo_queue', table_name='recognition_photo')
    op.drop_table('recognition_photo')
    op.drop_index(op.f('ix_import_job_task_id'), table_name='import_job')
    op.drop_index(op.f('ix_import_job_status'), table_name='import_job')
    op.drop_table('import_job')
    op.drop_index(op.f('ix_recognition_task_task_no'), table_name='recognition_task')
    op.drop_index(op.f('ix_recognition_task_status'), table_name='recognition_task')
    op.drop_table('recognition_task')
    op.drop_index(op.f('ix_oss_upload_cache_file_sha256'), table_name='oss_upload_cache')
    op.drop_table('oss_upload_cache')
    # ### end Alembic commands ###
