"""add qc confidence

Revision ID: 43577b41f8fd
Revises: 2667d594ebe6
Create Date: 2026-09-22 13:28:22.486574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43577b41f8fd'
down_revision: Union[str, Sequence[str], None] = '2667d594ebe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qc_result', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qc_result', 'confidence')
    # ### end Alembic commands ###
